# Generated by Django 4.0.3 on 2022-05-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_post_numviews_alter_post_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
    ]
