# Generated by Django 4.0.4 on 2022-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
