# Generated by Django 4.0.3 on 2022-04-10 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='now',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
