# Generated by Django 4.0.3 on 2022-04-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_post_now_alter_post_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='now',
        ),
    ]
