# Generated by Django 4.0.4 on 2022-07-31 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('time1', models.DateTimeField(default=datetime.datetime.now)),
                ('time2', models.DateTimeField(null=True)),
                ('time3', models.DateTimeField(null=True)),
                ('finalTime', models.DateTimeField(null=True)),
                ('msg', models.TextField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_registers', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='main.post')),
            ],
            options={
                'ordering': ('post', 'created_dt'),
            },
        ),
    ]
