# Generated by Django 4.0.3 on 2022-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_aritcle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Hobby', max_length=100),
            preserve_default=False,
        ),
    ]
